# Site settings
title: Yumi Hong
tagline: 유미홍닷컴
description: 디자이너와 개발자의 그 사이
url: "https://yumihong.com"
author:
  name: "Yumi Hong"
  email: "iam@yumihong.com"
  url: "https://yumihong.com"

# Build settings
baseurl: {{ site.github.url }}
markdown: kramdown
destination: /_site  # 이 부분 삭제
permalink: /:title  # 이 부분 삭제
paginate: 8
paginate_path: /page:num/  # 이 부분 삭제

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-maps

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# 블로그 disqus shortname
disqus:
  shortname: yumihong
